### ISSUE TITLE
small nitpick about collision detection

### ISSUE THREAD

**Issue by rsarson** [Yousaf-Wajih/raycaster#1]
I've been learning from https://lodev.org/cgtutor/raycasting.html and came across your site while trying to improve Lode's "very primitive collision detection", as he calls it (see part 4 of the tutorial).  I initially experimented with my own version of using an offset but discovered a limitation of it, which your code (player.cpp) also exhibits:

If you head straight towards the corner of a wall but strafed even slightly outside of it, the offset calculations will not detect the wall.  This can be seen more clearly if you try a player size with something like .45

My solution is currently to use a hit box for the player, as seen in https://killerrobotics.me/tag/wolfenstein-3d/

I am also going to try to use a circle around the player as suggested by Lode, and similar to Lazy Foo's method (https://lazyfoo.net/tutorials/SDL/29_circular_collision_detection/index.php), but this has proven to bit more challenging for me at this point

Anyway, as the title suggests, it's just a nitpick... I actually think your project is pretty cool, especially the level editor!

**Comment by Yousaf-Wajih** [comment]
Yes, that behavior happens because the "offset" forms an AABB, which is (obviously) not rotated. Using a circle seems like a better approach. I'll look into it as soon as possible.

**Comment by Yousaf-Wajih** [comment]
Well, I don't think the rotation was the problem. It is actually because we only compare the origin when doing the test for the collision. When moving in the x-axis, we need to run a loop for the y-axis. And when moving on the y-axis, we need to run a loop on the x-axis. It should be fixed now. Also, I added a 2D visualization (press Tab) to make it work.
