### ISSUE TITLE
Stuck in the implementation

### ISSUE THREAD

**Issue by zerocool-m12** [Yousaf-Wajih/raycaster#2]
Hi brother Yousaf,

Thank u so much for ur educational videos.

I am the one who commented in ur YT channel asking for ur e-mail.

However, I am trying to make a raycasting with a little map in the corner like for example GTA, but the thing is the results is terrible! I will appreciate it a lot if u kindly review my code to correct what's wrong with it.

Here is below the link of my code:

https://github.com/zerocool-m12/Raycasting/tree/main

**Comment by Yousaf-Wajih** [comment]
I'll open an issue on your repo.
